apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "welltrack-frontend.fullname" . }}
  labels:
    {{- include "welltrack-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "welltrack-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "welltrack-frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          envFrom:
            - secretRef:
                name: {{ include "welltrack-frontend.fullname" . }}-env-secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}