{{- /* Check if ingress object exists AND if it's enabled */}}
{{- if and .Values.ingress .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "welltrack-frontend.fullname" . }}
  labels:
    {{- include "welltrack-frontend.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  {{- range .Values.ingress.hosts }} # Loop through each host entry
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }} # Loop through each path entry for the host
          - path: {{ .path | quote }}
            pathType: {{ .pathType | quote }}
            backend:
              service:
                name: {{ include "welltrack-frontend.fullname" $ }} # Use $ for root context
                port:
                  name: http
        {{- end }}
  {{- end }}
{{- /* TODO: Add TLS configuration if needed, iterating through .Values.ingress.tls */}}
{{- end }}