replicaCount: 1
image:
  # 使用 Docker 主机 IP 代替主机名
  repository: ghcr.io/hongda-zhu/welltrack-frontend
  tag: 3641d37
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: nginx
  host: frontend.welltrack.local
  path: /
  pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
# 添加镜像拉取凭证
imagePullSecrets:
  - name: harbor-credentials
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
