# Valores por defecto para welltrack-frontend.
# Este es un archivo con formato YAML.
# Declara variables que se pasarán a tus plantillas.
# Comentarios anteriores eliminados o traducidos/integrados donde sea relevante.

replicaCount: 1
image:
  # Repositorio correcto apuntando a GitHub Container Registry
  repository: ghcr.io/salieeriw/welltrack-frontend
  # La etiqueta será actualizada por el pipeline de CI
  tag: 4a138aa # Etiqueta por defecto, CI debería sobrescribir esto
  pullPolicy: Always
serviceAccount:
  # Especifica si se debe crear una cuenta de servicio
  create: true
  # Anotaciones para añadir a la cuenta de servicio
  annotations: {}
  # El nombre de la cuenta de servicio a utilizar.
  # Si no se establece y create es true, se genera un nombre usando la plantilla fullname
  name: ""
service:
  type: ClusterIP
  port: 3000 # Puerto en el que escucha el contenedor del frontend
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer # Anotación para cert-manager
  hosts:
    - host: app.welltrack.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - app.welltrack.local
      secretName: app-welltrack-local-tls # Secreto de Kubernetes para almacenar el certificado TLS
resources: {}
# Generalmente recomendamos no especificar recursos por defecto y dejar esto como una decisión consciente
# para el usuario. Esto también aumenta las posibilidades de que los charts se ejecuten en entornos con escasos
# recursos, como Minikube. Si deseas especificar recursos, descomenta las siguientes
# líneas, ajústalas según sea necesario y elimina las llaves después de 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
envSecrets:
  GOOGLE_CLIENT_ID: 486049524655-kv9hjekqeqk47l4mblrp9o40sobrtl54.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: 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
  NEXTAUTH_SECRET: muysecreto
  NEXTAUTH_URL: http://app.welltrack.local:3000
