replicaCount: 1

image:
  # 使用 Docker 主机 IP 代替主机名
  repository: 172.17.0.1:3000/welltrack/welltrack-frontend
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: nginx
  host: frontend.welltrack.local
  path: /
  pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

resources:
  requests:
    cpu: 1.5
    memory: 2Gi
  limits:
    cpu: 1.5
    memory: 2Gi