replicaCount: 1

image:
  # 使用 Docker 主机 IP 代替主机名
  repository: 172.17.0.1:80/welltrack/welltrack-frontend
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  host: frontend.welltrack.local
  path: /
  pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

# 添加镜像拉取凭证
imagePullSecrets:
  - name: harbor-credentials

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi