replicaCount: 1
image:
  repository: ghcr.io/hongda-zhu/welltrack-backend
  tag: 8ac979c
  pullPolicy: Always
service:
  type: ClusterIP
  port: 8080
resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 500m
    memory: 2Gi
