replicaCount: 1
image:
  repository: ghcr.io/salieeriw/welltrack-backend
  tag: dec9578
  pullPolicy: Always
service:
  type: ClusterIP
  port: 3001
resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 500m
    memory: 2Gi
envSecrets:
  SUPABASE_URL: https://mnjyjbrizrvlzgecgybl.supabase.co
  SUPABASE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
  ML_BASEURL: http://ml.welltrack.local:5000
  RESEND_API_KEY: re_BPhFZCWK_KYz1dxvpkFMmNxAf1i8VJFwD

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
  hosts:
    - host: api.welltrack.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - api.welltrack.local
      secretName: api-welltrack-local-tls

nodeSelector:
  tipo: backend
