replicaCount: 1
image:
  repository: ghcr.io/hongda-zhu/welltrack-backend
  tag: 4a3e082
  pullPolicy: Always
service:
  type: ClusterIP
  port: 3001
resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 500m
    memory: 2Gi
# Credenciales de la base de datos
# ADVERTENCIA: ¡Almacenar secretos en texto plano en Git es inseguro para producción!
# Considere usar Helm Secrets u otros métodos seguros para entornos de producción.
databaseCredentials:
  username: "user" # Reemplazar con el nombre de usuario real
  password: "password" # Reemplazar con la contraseña real
  host: "postgresql.database.svc.cluster.local" # Reemplazar con el host real (p.ej., del servicio del chart de base de datos)
  port: "5432" # Reemplazar con el puerto real
  database: "welltrackdb" # Reemplazar con el nombre de la base de datos real
# Configuración de Ingress para el backend
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer # Anotación para cert-manager
  hosts:
    - host: api.welltrack.local # Nombre de host para la API del backend
      paths:
        - path: / # Ruta base para la API
          pathType: Prefix
  tls:
    - hosts:
        - api.welltrack.local
      secretName: api-welltrack-local-tls # Secreto de Kubernetes para almacenar el certificado TLS
