replicaCount: 1
image:
  repository: ghcr.io/salieeriw/welltrack-backend
  tag: a9499b4
  pullPolicy: Always
service:
  type: ClusterIP
  port: 3001
resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 500m
    memory: 2Gi
# Configuración de Ingress para el backend
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer # Anotación para cert-manager
  hosts:
    - host: api.welltrack.local # Nombre de host para la API del backend
      paths:
        - path: / # Ruta base para la API
          pathType: Prefix
  tls:
    - hosts:
        - api.welltrack.local
      secretName: api-welltrack-local-tls # Secreto de Kubernetes para almacenar el certificado TLS
