replicaCount: 1

image:
  repository: harbor.welltrack.local/welltrack/welltrack-backend
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080
  
resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 500m
    memory: 2Gi