replicaCount: 1

image:
  repository: harbor.welltrack.local/welltrack/welltrack-backend
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080
  
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi