# PTI-WellTrackGitOps/charts/welltrack-backend/templates/secrets.yaml
{{- if .Values.databaseCredentials }}
apiVersion: v1
kind: Secret
metadata:
  # Use the same name pattern expected by the deployment
  name: {{ include "welltrack-backend.fullname" . }}-db-secret
  labels:
    {{- include "welltrack-backend.labels" . | nindent 4 }}
type: Opaque
data:
  # The keys here (DB_USERNAME, etc.) must match the keys expected by your application's environment variables
  # The values are taken from values.yaml and base64 encoded as required by Kubernetes Secrets
  DB_USERNAME: {{ .Values.databaseCredentials.username | b64enc | quote }}
  DB_PASSWORD: {{ .Values.databaseCredentials.password | b64enc | quote }}
  DB_HOST: {{ .Values.databaseCredentials.host | b64enc | quote }}
  DB_PORT: {{ .Values.databaseCredentials.port | b64enc | quote }}
  DB_NAME: {{ .Values.databaseCredentials.database | b64enc | quote }}
{{- end }} 